name: Flake8 Check, Tests, and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flake8-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the current directory
      run: ls -R  # Выводим содержимое текущего каталог

    - name: Print current working directory
      run: pwd
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt не найден!"
        fi
        pip install flake8

  test:
    runs-on: ubuntu-latest
    needs: flake8-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x



      - name: List files in the current directory
        run: ls -R  # Рекурсивный вывод содержимого каталогов

      - name: Find requirements.txt
        run: find . -name requirements.txt  # Поиск файла requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE testdb;"  # Создание тестовой базы данных
          sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD '12345';"  # Создание пользователя
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO postgres;"  # Предоставление прав

      - name: Run tests
        run: |
          pytest --alluredir=allure-results  # Запуск тестов и сохранение результатов Allure

      - name: Upload Allure results
        uses: actions/upload-artifact@v3  # Обновленная версия
        with:
          name: allure-results
          path: allure-results

  # Собрать и отправить образ приложения на DockerHub
  build:
    runs-on: ubuntu-latest
    needs: test  # Замените на "test", чтобы зависеть от предыдущего шага
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: esseniya/testrepo:latest
