name: CI/CD

on:
  push:
    branches:
      - main  # Запускается при каждом push в главную ветку
  pull_request:
    branches:
      - main  # Запускается при каждом pull request к главной ветке

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Укажите вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Убедитесь, что у вас есть requirements.txt

    - name: Run tests
      run: |
        pytest -m "test_task"  # Замените на вашу команду для тестов

    - name: Deploy
      run: |
        echo "Deploying to production..."  # Замените на вашу команду развертывания
