name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Обновляем до версии v3

    - name: Set up Python
      uses: actions/setup-python@v3  # Обновляем до версии v3
      with:
        python-version: '3.11'  # Укажите вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -m "test_task"

    - name: Deploy
      run: |
        echo "Deploying to production..."
